import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#5341cd",
        "primary-container": "#6c5ce7",
        "on-primary": "#ffffff",
        "on-primary-container": "#faf6ff",
        "primary-fixed": "#e4dfff",
        "primary-fixed-dim": "#c6bfff",
        "on-primary-fixed": "#160066",
        "on-primary-fixed-variant": "#4029ba",
        secondary: "#5d5d6b",
        "secondary-container": "#e0deef",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#61616f",
        "secondary-fixed": "#e2e1f1",
        "secondary-fixed-dim": "#c6c5d5",
        "on-secondary-fixed": "#1a1b26",
        "on-secondary-fixed-variant": "#454653",
        tertiary: "#595574",
        "tertiary-container": "#726d8e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#faf5ff",
        "tertiary-fixed": "#e5deff",
        "tertiary-fixed-dim": "#c9c2e7",
        "on-tertiary-fixed": "#1b1834",
        "on-tertiary-fixed-variant": "#474362",
        surface: "#f4fafd",
        "surface-dim": "#d4dbdd",
        "surface-bright": "#f4fafd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef5f7",
        "surface-container": "#e8eff1",
        "surface-container-high": "#e2e9ec",
        "surface-container-highest": "#dde4e6",
        "on-surface": "#161d1f",
        "on-surface-variant": "#474554",
        "inverse-surface": "#2b3234",
        "inverse-on-surface": "#ebf2f4",
        "inverse-primary": "#c6bfff",
        outline: "#787586",
        "outline-variant": "#c8c4d7",
        "surface-tint": "#5847d2",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f4fafd",
        "on-background": "#161d1f",
        "surface-variant": "#dde4e6",
        // Custom brand colors
        lavender: "#F0EEFF",
        "border-input": "#E0D9FF",
        // India tricolor
        saffron: "#FF9933",
        "india-green": "#138808",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["22px", { lineHeight: "28px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500", letterSpacing: "0.01em" }],
        "label-caps": ["11px", { lineHeight: "16px", fontWeight: "700", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        base: "4px",
      },
      boxShadow: {
        "primary-glow": "0 4px 20px -2px rgba(83, 65, 205, 0.25)",
        "card": "0 2px 8px rgba(0, 0, 0, 0.05)",
        "card-hover": "0 8px 24px rgba(0, 0, 0, 0.1)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.4s ease-out",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
        shimmer: "shimmer 1.5s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      maxWidth: {
        "mobile": "375px",
        "form": "480px",
      },
    },
  },
  plugins: [],
};

export default config;
